const SET_SELECTED_GAME = 'ADD_SELECTED_GAME'
const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
const SET_DURATION_TEXT = 'SET_DURATION_TEXT'
const SET_DROPDOWN = 'SET_DROPDOWN'

export { SET_SELECTED_GAME, SET_SEARCH_TEXT, SET_DURATION_TEXT, SET_DROPDOWN }
